version: 2
formats: []

build:
  os: ubuntu-22.04
  tools:
    python: "3"  # latest stable cpython version

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements-docs.txt