 name: Bug Reports
 description: Create a report to help us improve
 labels: [bug]
 body:
  - type: input
    attributes:
     label: Title
     description: >
      A short summary of what your feature request is.
    validations:
     required: true
  - type: input
    attributes:
     label: what is your bale bot version?
    validations:
     required: true
  - type: textarea
    attributes:
     label: Reproduction Steps
     description: >
      What you did to make it happen.
    validations:
     required: true
  - type: textarea
    attributes:
     label: System Information
    validations:
     required: false
  - type: textarea
    attributes:
     label: Exception Result
     description: What did you expect to happen?
    validations:
     required: true